# Generated by Django 3.2 on 2022-04-15 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notesmodel_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesmodel',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
